<nav class="navbar navbar-expand-lg navbar-light bg-success">
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="index.php" id="" role="" data-bs-toggle="" aria-expanded="false">
                        VOLVER A INICIO
                    </a>
                </li>
            </ul>
        </div>
        |
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="public/imgs/favicon.png" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
            MIMOUN MARKET SL
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

    </div>
</nav>